# Generated by Django 6.0 on 2026-02-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_rename_price_product_mrp_product_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to='carousel_ads/')),
                ('link', models.URLField(help_text='URL of product or page', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
