# Generated by Django 3.2.14 on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0012_orders_razorpay_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderupdate",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
