# Generated by Django 3.2.14 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0013_orderupdate_cancelled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "section_name",
                    models.CharField(
                        help_text="Category name shown on homepage. Match product category for direct section landing.",
                        max_length=120,
                    ),
                ),
                ("image", models.ImageField(upload_to="shop_categories/")),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Shop Category",
                "verbose_name_plural": "Shop Categories",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
